---
title: A collection of links to AI resources
subtitle: ""
---





# Overview
This unit consists mainly of a collection of links to AI resources that might be useful. I tried to group them into themes and provide a bit of commentary. The focus is on generative AI tools.

# Learning Objectives
By the end of the unit, you should:

* Be aware of a few places where you can learn more about AI.


# Introduction


# AI in general

* [One Useful Thing](https://www.oneusefulthing.org/) is a Substack blog by Ethan Mollick where he discusses ideas around (generative) AI from a very applied user perspective. You might find a lot of what he writes echoed in my writing, because that's where I get a lot of my information from 😁.

* [Unconfuse Me](https://www.gatesnotes.com/Podcast) is a podcast by Bill Gates that covers all kinds of topics, but has a few interesting AI-themed ones, namely (as of this writing) episodes 2 and 5.

* [DeepLearning.AI](https://www.deeplearning.ai/) is a platform/company that offers a lot of teaching material related to AI. Some of the materials are free.

* A really good (but non-free) book is [*Artificial Intelligence: A Guide for Thinking Humans*](https://melaniemitchell.me/aibook/). The author, Melanie Mitchell, also has [an AI blog](https://aiguide.substack.com/) that is worth checking out.

* This [Coursera course](https://www.coursera.org/learn/generative-ai-for-everyone) gives a brief, non-technical introduction to current LLM AI tools (such as GPT).


# Technical aspects of AI 

* The [Deep Learning Chapter of *HMLR*](https://bradleyboehmke.github.io/HOML/deep-learning.html) provides a nice basic introduction. 

* The [Statquest Youtube channel](https://www.youtube.com/@statquest) has multiple videos with nice explanations on various AI related topics, at times going fairly deep into the technical details, while still being rather easy to understand. 

# AI and R

* These [materials from a recent workshop by Phil Bowsher](https://github.com/philbowsher/Workshop-R-Tensorflow-Scientific-Computing) describe using Tensorflow to do deep learning/AI in R.



# AI and teaching


- [Wharton Interactive](https://interactive.wharton.upenn.edu/teaching-with-ai/) is an initiative by Ethan and Lilach Mollick and colleagues at Wharton that - among other things - looks at the use of AI for teaching and learning. The website contains some interesting ideas and links to papers that look further into AI use.


# AI and Coding






