---
title: Model assessment
subtitle: ""
---


# Overview
Critical thinking is important. That also applies to your (or someone else's) models.

This module discusses ways to assess your models. 

# Learning Objectives

* Be familiar with methods to assess models.
* Be able to perform model assessment on your own and others' models.

# Content

The module consists of the following units:

* [Model assessment introduction](./model-assessment-introduction/model-assessment-introduction.qmd)
* [Reality-based assessment](./reality-based-assessment/reality-based-assessment.qmd)
* [Model performance revisited](./model-performance-revisited/model-performance-revisited.qmd)
* [Model evaluation with cross-validation](./external-data-assessment/external-data-assessment.qmd)
* [Model evaluation with Information Criteria](./information-criteria-assessment/information-criteria-assessment.qmd)
* [Model diagnostics](./diagnostics-assessment/diagnostics-assessment.qmd)
* [Model uncertainty](./uncertainty-assessment/uncertainty-assessment.qmd)

<!-- * [Model documentation](./model-documentation/model-documentation.qmd) -->
<!-- * [R tools for performance assessment](./assessment-r-tools/assessment-r-tools.qmd) -->

