---
title: Assessment - Machine Learning Models 2
subtitle: ""
---

# Quiz

Get the quiz sheet for this module from the general
[**Assessments**](../../courseinfo/assessments-overview.qmd) page. Fill it
in, then submit to the online grading system before the deadline.

# Project

Submission of part 4 is due. Make sure your updated project is on
GitHub.

# Discussion

Write a post in this week’s discussion channel that answers this question:

Which of the machine learning methods we covered (or any we didn't cover but you are aware of) do you find most exciting/interesting and why? And which ML method seems the most confusing/pointless to you, and why? Are there any ML approaches you want to learn more about and need more resources beyond those provided on the website?

Post by Wednesday, then reply to each other by Friday. 

# Exercise

Since this week is another week with a project submission deadline, there's no exercise. You can practice some of the models we covered this week in next week's exercise.


