---
title: Currently available AI tools
subtitle: ""
---



# Overview
In this tutorial, we discuss some currently available LLM AI tools and when/how you might want to use them. This is of course a rapidly moving field, so a few months from now things might have changed. I can hopefully keep up somewhat, but check the last modified date of this page 😁.


# Goals
By the end of the tutorial, you should:

* Be familiar with current AI tools and when/how to use them.


# Introduction




# OpenAI ChatGPT

As of this writing, for the AI tools we are interested in (the LLMs), ChatGPT is probably the most useful tool. You can access it by creating a [free account](https://chat.openai.com/).

ChatGPT is also part of the Microsoft [Bing search engine](https://www.bing.com/) (currently located oder the "Chat" tab) and [GitHub's CoPilot](https://github.com/features/copilot).


If you haven't already, I suggest you create a ChatGPT/OpenAI account. As of this writing, you can get a [free account](https://chat.openai.com/). Once you log in, you see a fairly plain interface with an area into which you can type your prompts. You can provide fairly elaborate prompts, and ask for code. For instance, try placing this into the bar:

*Write R code that generates a dataset of 100 individuals with ages from 18 to 49, BMI values from 15 to 40 and smoking status as yes or no. Assume that age and BMI are uncorrelated. Assume that smokers have a somewhat lower BMI. Then use the patchwork R package to generate a panel of ggplot2 plots. The first panel should show a violin plot with BMI on the y-axis and smoking status on the x-axis. The second panel should show a scatterplot with age on the y-axis and BMI on the x-axis. Add thorough documentation to your code.*

When I did that, ChatGPT gave me this [fully working code](../../media/ChatGPT_example.R). It is possible that when you run it, the code will look slightly different (see the comment below on non-reproducibility). Hopefully, what you get will run. If not, you might need to either fix the code or ask the AI to fix it.


# Bing (still OpenAI GPT)

A free OpenAI account gives you access to ChatPGT 3.5. While I find it often quite useful, especially for writing code, it's not the best AI out there. ChatGPT 4.0 is generally better. You have to pay OpenAI if you want to use it. Or, you can go to Microsoft's Bing website [and use it for free](https://www.bing.com/). (Click on the "Chat" icon.) [It is recommended](https://www.oneusefulthing.org/p/an-opinionated-guide-to-which-ai) to use Bing's AI in "Creative" or "Precise" mode. Of course feel free to explore and play around.



# GitHub Copilot

GitHub Copilot is currently free for students with the [GitHub student developer pack](https://education.github.com/pack) I asked you to sign up for. Set it up by following the [Quickstart guide](https://docs.github.com/copilot).

Once you have Copilot activated, you can use it in R Studio. (It is also possible to use it with other popular editors, such as VS Code, but for this course I will focus on R Studio. If you prefer to code in VS Code, you can install the Copilot plugin).

To get Copilot working in R Studio, follow these [instructions](https://docs.posit.co/ide/user/ide/guide/tools/copilot.html). You might want to leave Copilot indexing unchecked for now. The instruction guide explains what this is. See the note on confidentiality issues below why you might not want to turn it on. Once you have co-pilot up and running, you should see it show up in the bottom of your R Studio input window (the top right window where you write code). It will start suggesting things as you type, once you stop for a few seconds. You can set that time in the options.

For some more eloquent use of Copilot, see the [video](https://youtu.be/yVq-b5xHmac?si=DPJXXnEoViVFYA1T) by Thomas Mock from Posit/RStudio. It's a bit long, but I highly recommend you watch it. Efficient use of AI in general and Copilot specifically will likely save you a lot of time for the rest of this course!

**In general, I recommend you turn off Copilot in RStudio when you are not actively using it.** And before you turn it on, make sure the document you have open, and any other files it might have access to, do not contain information you want to keep private.


# Other tools

As you learned from Thomas Mock's video above, the [`chattr` R package](https://mlverse.github.io/chattr/) is another great way to use ChatGPT from within R. I recommend exploring it.

As you are probably aware, these AI tools are changing rapidly. I'm writing this in November 2023, you will read this a few months later. It could be that at this point, some new versions of AI tools have come out that are even better. Do explore and if you find some especially promising platform or package, let me know!


# Summary


# Further Resources

For a list and description of some other AI tools, see this [guide on using AI to do stuff](https://www.oneusefulthing.org/p/how-to-use-ai-to-do-stuff-an-opinionated).



