---
title: Course Project Examples 
subtitle: ""
---

# Overview

To showcase some of the work previous students have done, and as
inspiration of future projects, below you can find links to a selection
of past projects. Of course, all are posted with permission from the
students.

(I only decided to ask students if I can showcase some of their projects
in 2021, so currently that's the only year that has examples.)

# 2021 Projects

-   *Plastic in the Urban Freshwater Environment* by [Amelia
    Foley](https://ameliafoley.github.io/AMELIAFOLEY-MADA-portfolio/) -
    [main report](projectexamples/Foley_Report.html), [supplement
    file](projectexamples/Foley_Supplement.html), [GitHub project
    repository](https://github.com/ameliafoley/AmeliaFoley-MADA-project).

-   *Predicting Federal Emergency Management Agency Funding for U.S.
    Disasters* by [Morgan
    Taylor](https://morganataylor.github.io/MorganTaylor-MADA-portfolio/index.html) -
    [main report](projectexamples/Taylor_Report.html), [supplement
    file](projectexamples/Taylor_Supplement.html), [GitHub project
    repository](https://github.com/morganataylor/MorganTaylor-MADA-project).
