---
title: MADA – Spring 2024 – Schedule
subtitle: ""
toc: FALSE
---

This is the current course schedule for the class. Things might change, so check regularly for updates.

The *Assessments* column lists items that need to be submitted and that will be graded. Those are described in more detail in an [**Assessments**](assessments-overview.qmd) page and in the assessment document for each module.

::: emphasis
Unless otherwise specified, the first posting of the discussion is due by end of Wednesday, the discussion replies are due by end of Friday. Quizzes are due by Friday. Exercises often have multiple parts with staggered deadlines. See each exercise for details.
:::


| **Module Topic**                                  | **Start and end dates** | **Assessments**                                            |
|---------------------------------------------------|-------------------------|------------------------------------------------------------|
| Module 1 -- Course and tools introduction         | 1/8 -- 1/12             | quiz, exercise, discussion                       |
| Module 2 -- Data analysis introduction            | 1/15 -- 1/19            | quiz, exercise, discussion    |
| Module 3 -- R coding basics                       | 1/22 -- 1/26            | quiz, exercise, discussion            |
| Module 4 -- All about data                        | 1/29 -- 2/2             | quiz, exercise, **project part 1**    |
| Module 5 -- Data processing                       | 2/5 -- 2/9              | quiz, exercise, discussion            |
| Module 6 -- Presenting data                       | 2/12 -- 2/16            | quiz, exercise, discussion                                 |
| Module 7 -- Statistical analysis overview         | 2/19 -- 2/23            | quiz, discussion, **project part 2**                       |
| Module 8 -- Fitting basic statistical models      | 2/26 -- 3/1             | quiz, exercise, discussion                                 |
| **Spring Break**                                  | **3/4 -- 3/8**          |                                                            |
| Module 9 -- Evaluating your model fits            | 3/11 -- 3/15            | quiz, discussion, **project part 3**                       |
| Module 10 -- Improving your model fits            | 3/18 -- 3/22            | quiz, exercise, project part 3 review |
| Module 11 -- Machine learning models I            | 3/25 -- 3/29            | quiz, exercise, discussion                                 |
| Module 12 -- Machine learning models II           | 4/1 -- 4/5              | quiz, exercise, **project part 4**                         |
| Module 13 -- The complete analysis workflow       | 4/8 -- 4/12             | quiz, exercise, discussion                                 |
| Finishing Project                                 | 4/15 -- 4/19            | **project part 5** due Friday 4/21, 5pm                    |
| Project Reviews                                   | 4/22 -- 4/26            | project reviews due Friday 4/28, 5pm                       |
| Final project revision                            | 4/29 -- 5/3             | **project part 6** due Friday 5/5, 5pm                     |

*Note: Withdrawal deadline is Thursday 3/21.*

## Synchronous Zoom meetings

I will offer a weekly Zoom meeting (aka office hour). See the [**Communication**](course-communication.qmd) section for some more details. As described in the **Communication** document, if you don't join the Zoom meetings you are not missing any important information, these are just **completely optional** opportunities to ask for help/feedback etc.

You can find the Zoom link on Discord. The plan is to have weekly alternating times for those zoom meetings such that everyone is able to make the meeting at least every 2 weeks.

The current plan is to have **Zoom meetings for odd module numbers on Wednesdays at 8am, and for even module numbers on Tuesdays at 8am. The first Zoom session will be on Wednesday, 1/10 at 8am ET.**

Hopefully, at least one of those two times works for you, allowing you to join at least every other time if wanted. If you already know that neither times work for you, and you are keen on joining the Zoom meetings, let me know and we can adjust. 

