---
title: Course Communications
subtitle: ""
toc: FALSE
---

## Overview

-   The main course content can be found on this website.
-   We'll mostly communicate and discuss through Discord.
-   There will be completely optional Zoom sessions (aka office hours).
-   Some communication/interaction will happen via GitHub. More details are provided in the relevant sections.


## Discord

The main mode of communication will be through Discord.
You should have received an invite link to join the Discord server for this class.
If you haven't received an email by Friday before classes start or can't find the Discord invite link on eLC, let me know.

If you are unfamiliar with Discord, it is essentially a chat/discussion tool (similar to Slack or Teams or...).
The main area for the class is called a *server* in Discord.
Ours is called **MADA-Spring-2026**.
If you use Discord for other purposes, you might be a member of additional servers.
Each server has *channels*.
Each *channel* corresponds to a topic.
The names and descriptions of the different channels should be self-explanatory.

**Please set your Discord profile for our server to your full name (first and last). Also, add an image of yourself to the profile.** It will help make things a bit more personal and social, even if it's not quite the same as in-person. You can do all that if you right-click your user name and choose **Edit Server Profile**. _Doing so will adjust things just for our server. If you use Discord for other purposes and don't want to use your real name on other servers, make sure you change the **per-server profile**._ In contrast, if you want to change your user name/image and other details for all your Discord servers, you would adjust it under `Main Profile`.


If a channel is public, you can see it and participate in the discussion.
For private channels you need an invite to see it and participate.
For simplicity, all channels are public, though there will be channels which likely won't be of interest to you.
Specifically, you'll be placed into groups during the course and will likely only be interested in the channel for your group.
If you have requests for specific channels to be created, let me know.

Inside a channel, you can write messages.
To respond to someone's message you should reply as thread so it's clear which messages go together.

You can also use Discord to send one or more individuals direct messages (DM).
You can use that to communicate with me or each other.

Overall, Discord is fairly intuitive, and hopefully much easier to use than the rather clunky discussion feature of eLC.
If you have no previous Discord experience, I suggest you browse through [their very comprehensive documentation](https://support.discord.com/hc/en-us) to pick up a few tips and tricks.

One useful thing to know is that people will get a specific notification if you either send them a direct message or use their handle in our message, e.g. by writing `@personname can you take a look at the figure below...`.
Specifically, if you want to get my attention, you need to do it that way. I have too many things pinging me all the time 😁.
While I try to stay on top of all the messages in our class, I likely won't.
To ensure I don't miss something directed at me, use the \@ notation (or DM).

**I will use the *announcements* channel to post any important course related announcements. Check regularly.**

Use Discord widely to ask questions, to answer others' questions, to notify me and others of things that are unclear/wrong, to post links to interesting resources, etc. I hope we can build a *community of learners* where you help and support each other.
So please don't always wait for me to answer questions or provide feedback, instead, engage with each other!
I will regularly visit and read the discussions and participate, but I hope that I will end up as one participant of many, not the only person providing answers.

In general, I prefer that you use the `questions-help` Discord channel to ask questions.
The reason is that if you have a question, it is likely that others have it too.
By asking and answering online, everyone can see it. You might also get a quicker reply since everyone can answer.
That said, there might be instances where the question only relates to you or is personal. In such cases, feel free to either send me a direct message on Discord or email me.


## Zoom

I will offer a weekly Zoom meeting (aka office hour). 

Those are **completely optional.** To ensure everyone will be able to join at least occasionally, I plan to alternate between two times each week. 

The current plan is to have **Zoom meetings for odd module numbers on Thursdays at 8am, and for even module numbers on Wednesday at 8am. The first Zoom session will be on Thursday, 1/15 at 8am ET.** You can find the Zoom link on Discord.

At the designated times, I will start the meeting. I'll wait around for 15 minutes. If nobody connects, I'll end the meeting. If people connect, we'll talk until we covered everything, or until I or you need to move on to our next appointments. 

I want to emphasize that the only use for these Zoom sessions is for me to be there and answer any questions you might have. There is no material covered, no announcements, or anything of that sort. Unless you have a question/topic that you want to discuss and that can't be addressed by posting it to Discord, there should be no reason for you to come to the Zoom meetings.

I will **not record** these meetings to ensure students feel comfortable discussing/asking anything they want to.
If any topic comes up that I think is worth sharing more widely, I will afterwards post a Discord message and/or add content to the website. Therefore, if you can't make these Zoom meetings, you are not missing anything other than the option of asking me questions that might be tricky to discuss on Discord.

And of course, if you have something you want to discuss outside of those weekly office hours, send me a message and we can schedule a meeting.



## GitHub

We will also use GitHub for some specific communications, related to exercises and projects.
More detailed instructions on that are provided at the time you are asked to use GitHub.

## eLC

We will not be using eLC.
I might occasionally use the *email everyone* feature in eLC to send out an email to the class in the first few weeks until everyone has settled into using Discord.
After that, I do not plan on using eLC and instead will communicate via Discord.


## Course Teaching Assistant

In some semesters, I have a TA for the class.
If there is a TA the semester you are taking the class, they will be another point of contact for you to ask questions.
The TA will be posting an introduction to Discord with details of their availability and preferred modes of communication (Discord/Zoom/etc.).
If no such posting shows up on Discord, it means there is no TA.

