---
title: Overview of the synthetic data content 
subtitle: ""
---


# Overview
This module covers why and how to generate and use synthetic (also known as simulated/artificial/fake) data.


# Learning Objectives

* Know about reasons why one might want to use simulated data.
* Be familiar with ways to generate synthetic data.
* Be aware of several R packages that can be used to generate synthetic data.
* Know how to use synthetic data for testing.
* Know how to use synthetic data with AI tools.


# Content

The module consists of the following units:

* [Introduction and Motivation](./synthetic-data-introduction/synthetic-data-introduction.qmd)
* [Creating new data](./synthetic-data-new-r/synthetic-data-new-r.qmd)
* [Creating new data based on existing data](./synthetic-data-new-existing-r/synthetic-data-new-existing-r.qmd)
* [Scrambling existing data](./synthetic-data-existing-r/synthetic-data-existing-r.qmd)
* [R packages for data creation](./synthetic-data-r-packages/synthetic-data-r-packages.qmd)
* [Use synthetic data with AI tools](./synthetic-data-ai-tools-r/synthetic-data-ai-tools-r.qmd)
* [Use synthetic data to test models](./synthetic-data-model-testing-r/synthetic-data-model-testing-r.qmd)


