---
title: Assessment - Course and Tools Introduction
subtitle: ""
---

# Reminder

Each module comes with assessments. Those are things you need to do that will be graded. The table on the [**Schedule**](../../courseinfo/course-schedule.qmd) page lists the assessments for each module.

If you haven't done so, please read through the [**Assessments Overview**](../../courseinfo/assessments-overview.qmd) page so you know how each type of assessment should be done and how grading works.

Each module has an **Assessments** page, like this one, which describes what the assessments are and what you should do. Often, there is a good bit of information for the exercises.

# Quiz

Get the quiz sheet for this module from the general [**Assessments**](../../courseinfo/assessments-overview.qmd) page. Fill it in, then submit to the online grading system before the deadline.

For this first module, you have 2 submission attempts. This allows you to get used to the submission system.


# Discussion

The discussion for this module is all about getting to know each other. For your original post, complete the Exercise below, then post the URL to the website you created by doing the exercise below into the `introductions` Discord channel. **Do so by Wednesday 5pm.**

For your replies, visit some of your classmates websites and leave feedback as a reply to their initial post. **Do so by the Friday deadline.**

I hope this will allow you to start getting to know each other, even if only virtually.

# Exercise

For this exercise, you are asked to use the tools you learned about to create a website which will become your portfolio for this class. You'll write and post a short personal introduction of yourself.


## Workload Note

For those of you who are new to Github/R/Quarto, this first project will make you do a lot of things that you are not familiar with. I know that this will be time-consuming and also might feel a bit intimidating. It's partly unavoidable and partly on purpose. You need to learn how to quickly get up to speed with all kinds of new tools that come your way. So practicing it is a good idea. You are welcome to draw on any sources for help that you want (online, classmates, instructor, etc.). I'm confident with a bit of trial and error you'll get it to work.

If you get stuck (quite possible), check the materials listed in the **Resources** section of the course, or use Google. Also use the discussion boards to ask questions. You may use any method to get help (Google, R4DS Slack channel, AI, colleagues/friends/relatives with R/Quarto/Markdown experience, etc.). Still, try to do as much as possible yourself. We'll use all the bits you are learning here repeatedly during this course.

## Pre-requisites

You should have gone through all content in this module and all relevant courses on the MDS site. 

## Instructions

To execute this exercise, follow the instructions in the [Portfolio Creation Course](https://andreashandel.github.io/mds-tools/courses/courses.html) on the MDS website.

::: emphasis
Once your website is up and running, don't forget to post the link into the `introductions` channel!
:::

