---
title: Quarto & Co
subtitle: ""
---

# Overview

This unit provides a brief introduction to the [Quarto system.](https://quarto.org/)

# Learning Objectives

-   Know what Quarto is good for
-   Be able to use Quarto for data analysis


# Introduction


# Quarto and R Markdown for reproducible analysis


R Markdown is still around and functional. For instance, this course website is written in R Markdown and [lives on GitHub](https://github.com/andreashandel/MADAcourse). But in my opinion, Quarto is the future. We'll therefore focus on using it. Eventually I'll switch all my materials over to Quarto. The good thing is that the transition is easy.

The idea behind Quarto is that you have a system that allows you to combine code with text and simple formatting to easily and reproducibly turn them into a lot of different output formats, e.g., HTML, PDF, Word, or slides. You can apply layout and styling to those documents, which is done separately from the content. This means you can quickly switch between outputs. Quarto calls [various other pieces of software](https://quarto.org/docs/get-started/hello/rstudio.html#how-it-works) to - almost magically - turn text and code input into a variety of different output formats. The good thing is, you generally don't need to care what goes on under the hood, it all happens (almost always) smoothly behind the scenes.

The input (for us) into a Quarto document are `R` code and Markdown text. Markdown is a simple way of formatting text to get some reasonably nice layouts with minimal effort. If you have no experience with Markdown, I suggest you go through this nice, short [interactive tutorial](https://www.markdowntutorial.com/). A good reference to look up formatting for Markdown until you have it memorized is this [online cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

**Quarto and R Markdown Note:** Quarto is fairly new. It didn't exist yet last time I taught the course. I'm switching to Quarto because I think it's the future. But you might still find me talking about R Markdown in some places. If you do, let me know so I can update. In general, either R Markdown or Quarto will do the job, but Quarto is the future, so it's best to use/learn it.

# Getting started with Quarto

The whole Quarto system is already incredibly flexible and powerful (and continues to grow). Because it is very feature rich and you can do a ton, trying to read all about it does not make much sense. The best is a *learn it as you need it* approach. The [Quarto website](https://quarto.org/) has great documentation, you'll likely be going there often.

To get started, follow the [get started guide](https://quarto.org/docs/get-started/) on the Quarto website. Install Quarto and - if you haven't already - R Studio. Then go through the 3 starter tutorials. There is already a lot going on in those tutorials, and there is no need to memorize it. The point is to get an idea of what you can do and play around a bit. You'll repeatedly be coming back to the Quarto documentation as you try to figure out how to do specific things. So if some of the material in the tutorials is not quite clear on your first pass-through, that's ok. Just get an overall idea and play around so you feel comfortable. You'll be using Quarto in the exercise (and pretty much all the time from now on).

<!-- One great thing about R Markdown is that it's well documented. The [R Studio R Markdown site](https://rmarkdown.rstudio.com/) and the [R Markdown book](https://bookdown.org/yihui/rmarkdown/) are great resources. Another good source targeted at scientists is the online book [R Markdown for Scientists](https://rmd4sci.njtierney.com/). RStudio also has an R Markdown cheat sheet in their [collection of very useful cheat sheets](https://www.rstudio.com/resources/cheatsheets/). -->

<!-- Since developing knitr and R Markdown, [Yihui Xie](https://yihui.name/en/) and colleagues have developed several other versions of the tool. There is [bookdown](https://bookdown.org/yihui/bookdown/) which lets you nicely add references and write full books and scientific manuscripts (see the research example in the introductory lesson and a list of books written in bookdown on the [bookdown website](https://bookdown.org/)) and [blogdown](https://bookdown.org/yihui/blogdown/) which lets you make webpages (see e.g. [my group webpage which is done that way](http://handelgroup.uga.edu/)).  -->

<!-- Some good sources that you might want to glimpse at are the chapters in the _Communicate_ section of the [R for Data Science book](http://r4ds.had.co.nz/index.html) and the beginning chapters of the [R Markdown book](https://bookdown.org/yihui/rmarkdown/). There's also the newer [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/), which is a good _how do I do X_ resource. -->

<!-- Again, you don't need to read these materials in much detail, but if you are new to R Markdown, try to get enough information so you understand what it's all about and how to get started. The way you learn R Markdown is by having a specific task you want to accomplish or a product you want to produce, and then look at various of the above listed documents to figure out how to do it. You'll get plenty of practice throughout this course. project. -->

# Other reproducibility tips

We'll cover that more later, but it is important to not do things that only work on your computer but not on others. The most important and frequent mistake I see is someone using a local path. If you load data from `C:\Users\myname\mydata` then it won't work for me. Always load/save data relative to the project folder. The [`here` R package](https://here.r-lib.org/) and its associated `here()` command in R is very useful. You'll see it show up and you should use it.

Another good idea is to start your R code with `use_blank_slate()` from the [`usethis` R package](https://usethis.r-lib.org/).

For some more background on this, see the [`tidyverse` article](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/) by Jenny Bryan, co-author of both the `here` and `usethis` packages.
