---
title: Tools for a READy workflow
subtitle: ""
---

# Overview

This unit covers some tools that can help with a READy workflow.


# Learning Objectives

- Be familiar with some tools that can help with a READy workflow.


# Introduction

There are many different ways to make a data analysis READy. The following is a brief discussion of some common tools.


# Version control software

Version control software, such as Git/GitHub, is used for tracking project changes and is discussed in the [Project Management](/content/module-ready-workflow/ready-project-management/ready-project-management.qmd) unit.


# Quarto

Quarto is tool that allows for easy scientific writing in a reproducible manner, by seamlessly integrating code with text. Quarto is further discussed in the [Quarto unit](/content/module-intro-tools/tools-quarto.qmd).


# Jupyter 

[Jupyter](https://jupyter.org/) is another platform that supports combining code with text. I'm not very familiar with it. As far as I understand it, it doesn't support the generation of different outputs that Quarto does. Since Quarto supports the same languages as Jupyter, I am not sure what the advantages are of using Jupyter. There might be some 😁.


# Sweave and such

There are some older tools, such as [`Sweave`](https://en.wikipedia.org/wiki/Sweave) that can also help in reproducible work. In my opinion they are made essentially obsolete by Quarto.


# Pipeline tools

Quarto and similar programs generally chain together a series of commands to get from the initial result to the final product. For instance for a Quarto file, when you render it, it first runs any code, then processes the markdown file, then turns it into the final product.

More generally, tools that allow you to automatically run such chains of steps are often referred to as pipeline tools. In R, there is the [`targets`](https://books.ropensci.org/targets/) package. Outside of R, Unix/Linux type systems support [`Make`](https://www.gnu.org/software/make/), which lets you combine multiple steps into often complicated workflows. If you find yourself needing a workflow that executes multiple different steps that go beyond what Quarto can execute, the `targets` package might be worth checking out.


# Other tools

In general, any software tool you use that allows you to document each step - usually in the form of code and comments - should allow others to reproduce your results. Many common software packages and languages such as Mathematica, Matlab, Julia, Python, etc. allow you to add documentation to your code and therefore support reproducibility.



# Hall of shame

There is a long list of software that is commonly used for research and data analysis, but which one should stay away from. This encompasses any software that does not contain a full documentation of all steps taken to allow reproducibility. 

**Excel** and similar spreadsheet software is a major culprit. If you make a change to data in an Excel file and save it, there is usually no track record of what happened. Therefore, any data processing that happens with Excel is not reproducible. 

Statistical and data analysis software that relies on graphical user interfaces (GUI), such as e.g. **Graphpad Prism** or **SPSS** are equally problematic. Some of these software tools can record the commands you perform through a GUI and you can save those at the end. This does allow for reproducibility. But if that step is missing or not implemented, the analysis is again not reproducible.

Similarly, any software to produce graphics by hand (e.g., **Photoshop**) should not be used. It is ok to use it make schematics, but not to edit any results.

Similarly, results tables should be generated automatically and not produced by copying and pasting numbers from one location to another. Again, that means no **Excel**.


# Summary

There are many useful tools that help you implement a READy workflow. The important part is that things are scripted, automated and repeatable, as well as documented. Any tools that support such a workflow are useful. Stay away from tools that require manual steps.


# Further Resources

None at the moment. Let me know if you come across any good ones that describe further tools.
